### ISSUE TITLE
Possible undefined behavior (std::erase_if)?

### ISSUE THREAD

**Issue by phprus** [greg7mdp/gtl#11]
Commit: https://github.com/greg7mdp/gtl/commit/f80aefde2b3b1b57c0cbf467f6897561e2f889ad

I think the ``std::erase_if`` overload might be undefined behavior.
Maybe it's better to use ADL (https://en.cppreference.com/w/cpp/language/adl) and declare ``erase_if`` in the ``gtl`` namespace?
Please check it.

Links:
https://en.cppreference.com/w/cpp/language/extending_std
https://stackoverflow.com/a/11599/590688

**Comment by greg7mdp** [comment]
Thanks @phprus I'll definitely check this (not right now though)

**Comment by greg7mdp** [comment]
Thanks again @phprus !
