### ISSUE TITLE
Inconsistency gtl versions

### ISSUE THREAD

**Issue by phprus** [greg7mdp/gtl#18]
Release - 1.1.3, but:

https://github.com/greg7mdp/gtl/blob/ba9386e76879da72910e44dc1fb6265f30285b67/include/gtl/gtl_config.hpp#L37-L39

**Comment by greg7mdp** [comment]
Thanks, I'll push a new version later today

**Comment by greg7mdp** [comment]
https://github.com/greg7mdp/gtl/releases/tag/v1.1.4

**Comment by greg7mdp** [comment]
Will push v1.1.4 to Conan later today.

**Comment by phprus** [comment]
Fixed by https://github.com/greg7mdp/gtl/releases/tag/v1.1.4
