### ISSUE TITLE
multimap

### ISSUE THREAD

**Issue by jmbnyc** [greg7mdp/gtl#19]
Greg,
Do you have plans to add a multimap variant for your flat hash map?

**Comment by greg7mdp** [comment]
Hi @jmbnyc , probably not any time soon. Could you use `flat_hash_map<K, std::vector<V>>`  instead of `multimap<K, V>`?

**Comment by jmbnyc** [comment]
Sure, but it would not be efficient esp when the majority of keys would have 1 value. My other thought was to do hash_map<K,V> where V is an address that comes from a spsc_queue<V> which consists of a linked list of arrays with a free list concept where I coopt the value to be a pointer in a linked list similar to an allocator free list (the map needs insert and erase).

Regardless, thanks for you quick response.

**Comment by greg7mdp** [comment]
Yes, in that case it would not be efficient. You could also try using `btree_multimap` from `btree.h`.

**Comment by jmbnyc** [comment]
I prototyped with btree_multiple but the lookup is way too slow esp for the not found case. I need consistent per if I have 10 keys or 1M keys.

**Comment by greg7mdp** [comment]
I'll close this because I don't expect to implement multimap support for the hash maps anytime soon.
