### ISSUE TITLE
Proposal: Remove duplication of standard declarations

### ISSUE THREAD

**Issue by phprus** [greg7mdp/gtl#20]
I am trying to remove duplicate and unused code in gtl.
Current state: https://github.com/phprus/gtl/tree/todo-1

I don't understand the need for declarations:
https://github.com/greg7mdp/gtl/blob/06e07a3538c42b2d5040866176916335deefaac2/include/gtl/phmap_fwd_decl.hpp#L36-L39

and

https://github.com/greg7mdp/gtl/blob/06e07a3538c42b2d5040866176916335deefaac2/include/gtl/phmap_fwd_decl.hpp#L59-L65

and

https://github.com/greg7mdp/gtl/blob/06e07a3538c42b2d5040866176916335deefaac2/include/gtl/gtl_base.hpp#L889-L909

Maybe replace these definitions with using std::allocator, std::pair, std::equal_to, std::less directly?

**Comment by greg7mdp** [comment]
If I remember correctly, it is because we want to be able to #include only `phmap_fwd_decl.hpp` (in a header file for example).

**Comment by phprus** [comment]
Yes, you are right for ``EqualTo`` and ``Less``.

``std::allocator (Allocator)`` and ``std::pair (Pair)`` are defined in ``<memory>`` and ``<utility>`` which are included in ``phmap_fwd_decl.hpp``. Maybe  removing this duplication?

**Comment by greg7mdp** [comment]
Is it really duplicated? We use `gtl::priv::Allocator` and `gtl::priv::Pair`, not the std versions.

**Comment by phprus** [comment]
Yes, but we can replace ``gtl::priv::Allocator`` and ``gtl::priv::Pair`` with std versions without negative effects. Additional headers will not need to be included.

Now I will make a PR with my suggestions for improving the code (without this replaces).
Please, review it.
